FROM php:8.2-fpm

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    nginx \
    supervisor \
    libpng-dev \
    libzip-dev \
    unzip \
    git \
    && docker-php-ext-install pdo pdo_mysql gd zip

# Instalar Composer
COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer

# Instalar Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug

# Copiar configuraciones
COPY etc/docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY etc/docker/php/php.ini /usr/local/etc/php/conf.d/custom.ini
COPY etc/docker/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Copiar aplicación
COPY . /var/www/html

# Configurar permisos
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Instalar dependencias de desarrollo
RUN composer install --optimize-autoloader --no-interaction

EXPOSE 80

CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]