services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: LaravelK8s_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    depends_on:
      - mysql
    networks:
      - bridge-network

  mysql:
    image: mysql:8.0
    container_name: LaravelK8s_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bridge-network

  webserver:
    image: nginx:alpine
    container_name: LaravelK8s_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./etc/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - bridge-network

volumes:
  db_data:
    driver: local

networks:
  bridge-network:
    driver: bridge